# Generated by Django 5.0.1 on 2024-02-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Code'),
        ),
    ]
