# Generated by Django 5.0.1 on 2024-02-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Item Code'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('item_code__isnull', False)), fields=('item_code',), name='unique_non_null_item_code'),
        ),
    ]
