# Generated by Django 5.0.1 on 2024-02-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='shop/documents/', verbose_name='Document file'),
        ),
    ]
