# Generated by Django 5.0.1 on 2024-02-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='shop/documents/', verbose_name='File'),
        ),
    ]
