# Generated by Django 5.0.1 on 2024-02-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_document_options_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Name'),
        ),
    ]
